version: "3.9"

networks:
  mcpnet:
    driver: bridge

services:
  playwright-mcp:
    image: mcr.microsoft.com/playwright/mcp:latest
    container_name: playwright-mcp
    shm_size: "2g"
    entrypoint: ["node", "cli.js"]
    command:
      [
        "--headless",
        "--browser", "chromium",
        "--no-sandbox",
        "--host", "0.0.0.0",
        "--port", "8931",
        "--user-data-dir", "/pw-user-data",
        "--isolated",
        "--allowed-hosts", "*",
        "--allowed-origins", "*",
        "--caps=vision,pdf,install"
      ]
    volumes:
      - ./exports:/tmp/playwright-output
    networks:
      - mcpnet
    restart: unless-stopped

  ui-tars-mcp:
    image: node:22-slim
    container_name: ui-tars-mcp
    shm_size: "1g"
    environment:
      - LANG=en_US.UTF-8
      - NODE_ENV=production
    command: >-
      bash -c "
      set -euo pipefail;
      apt-get update;
      apt-get install -y wget gnupg ca-certificates fonts-liberation libxss1 dbus dbus-x11;
      wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | gpg --dearmor -o /usr/share/keyrings/googlechrome-linux-keyring.gpg;
      echo 'deb [arch=amd64 signed-by=/usr/share/keyrings/googlechrome-linux-keyring.gpg] http://dl.google.com/linux/chrome/deb/ stable main' > /etc/apt/sources.list.d/google.list;
      apt-get update;
      apt-get install -y google-chrome-stable;
      npm install -g @agent-infra/mcp-server-browser@latest;
      mcp-server-browser --port 8000;
      "
    networks:
      - mcpnet
    restart: unless-stopped

  mcpo:
    build:
      context: ./mcpo
    image: mcpo-browser-agent:latest
    container_name: mcpo
    depends_on:
      - playwright-mcp
      - ui-tars-mcp
    volumes:
      - ./mcpo:/config
    entrypoint: ["/bin/sh", "-c"]
    command: >
      if [ ! -f /config/config.json ]; then
        mkdir -p /config &&
        echo '{
          "mcpServers": {
            "mcp_playwright": {
              "type": "streamable-http",
              "url": "http://playwright-mcp:8931/mcp"
            },
            "mcp_tars": {
              "type": "streamable-http",
              "url": "http://ui-tars-mcp:8000/mcp"
            }
          }
        }' > /config/config.json;
      fi;
      echo "✅ Config ready at /config/config.json";
      exec mcpo --config /config/config.json --host 0.0.0.0 --port 3879
    ports:
      - "3880:3879"
    networks:
      - mcpnet
    restart: unless-stopped

  screenshot-viewer:
    image: nginx:alpine
    container_name: screenshot-viewer
    depends_on:
      - playwright-mcp
    volumes:
      - ./exports:/usr/share/nginx/html:ro
    ports:
      - "3888:80"
    networks:
      - mcpnet
    restart: unless-stopped
